### ISSUE TITLE
Kubernetes migration

### ISSUE THREAD

**Issue by MrOctopus** [Akvanvig/MrRoboto#15]
# Move over to using kubernetes for bot deployment

- [x] Dockerfile
- [x] Docker image package
- [x] Kubernetes yaml file
- [x] Postgresql 
- [x] Quickstart.py
- [x] Local windows support
- [x] Local Debian support
- [x] Update readme

**Comment by audunsolemdal** [comment]
@assign audunsolemdal

**Comment by Akvanvig** [comment]
- Dockerfile created
- Image pushed to ghcr
- Kubernetes yaml configuration files created
- Postgresql deployment files added to kubernetes yaml configuration
- quickstart.py created with options for local setup and kubernetes setup
- Readme updated to reflect current setup process
