### ISSUE TITLE
Migrate media to volume

### ISSUE THREAD

**Issue by MrOctopus** [Akvanvig/MrRoboto#17]
Migrate media files to a volume.

Requires:
* Updates to quickstart.py
* Choosing a volume storage method
* Update kubernetes

**Comment by Akvanvig** [comment]
Version of image created [without audio-files created](https://github.com/users/Akvanvig/packages/container/package/mrroboto_no-audio)

Yaml config files Deployment_files\2_kube-storage.yaml and Deployment_files\4_kube-deployment.yaml modified to use a nfs share for audio files.
