### ISSUE TITLE
Remove Fredrik from this project!

### ISSUE THREAD

**Issue by andreashennestad** [Akvanvig/MrRoboto#21]
Fredrik has been quite rude to me lately. He told me that selling NorgesEnergi with a discount on mobile phones was a scam! I dont believe that I have to ACTUALLY tell the customer what they are signing up for!

**Comment by Looland** [comment]
I signed up for montly issue of VI men with Fredrik as the girl

**Comment by Akvanvig** [comment]
Controversial topic, closing this issue
