### ISSUE TITLE
Youtube stream returns generic error when there are noe results for query

### ISSUE THREAD

**Issue by Akvanvig** [Akvanvig/MrRoboto#25]
When there are no results for a search for youtube videos it returns the generic error:

> Command 'stream' is not working properly, contact your local developer :)

This should be changed to something more descriptive eg. "No results found for 'x' "

To reproduce:
?stream rylancdg stank

**Comment by MrOctopus** [comment]
I would like to add that this should be made a done inside the local command error handler, and not the bot wide one.

**Comment by Akvanvig** [comment]
Added a check for returned list containing no items 5d4c373e6cbc19a24187c2c6d999171b5d7d5894

Will now return the message `Could not find "rylancdg stank" on youtube` instead
