### ISSUE TITLE
Hide .txt file in git repo

### ISSUE THREAD

**Issue by MrOctopus** [Akvanvig/MrRoboto#26]
Call it MrRobotosway.txt, it has no purpose whatsoever and should never be deleted.
Its sole content will be the following sentence: "This is the MrRoboto way".

**Comment by Akvanvig** [comment]
This needs to be prioritized

**Comment by MrOctopus** [comment]
Any updates on the issue?

**Comment by MrOctopus** [comment]
No work, no pay
