### ISSUE TITLE
[SPRING BREAK][SPRING CLEANING] Fix songlist code

### ISSUE THREAD

**Issue by MrOctopus** [Akvanvig/MrRoboto#27]
Need to fix songlist to not mess up filepaths across operating systems.

**Comment by Akvanvig** [comment]
Did some cleaning in eab1fac78afec4f6fc3e938eb00122c26d5126d8

Got rid of two now unnecessary functions

**Comment by Akvanvig** [comment]
This is good enough for now, closing issue
