### ISSUE TITLE
Split weather function into separate cog

### ISSUE THREAD

**Issue by Akvanvig** [Akvanvig/MrRoboto#50]
Will combined with #49 make it possible to disable cog if required keys are not present

When this is done a rework of weather command should be done, to make it less of a hack.
Things like:
- Adding a default location (possibly through config file)
- Making a class object with functions to get more accurate data
- Accounting for timezones?
- Add hour by hour forecast as subcommand / separate command
- Maybe other data available through yr API ( See https://api.met.no/ )

**Comment by MrOctopus** [comment]
Fixed in 5209d2f
